-- MySQL Script generated by MySQL Workbench
-- Sat Nov 30 23:08:02 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`movies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`movies` ;

CREATE TABLE IF NOT EXISTS `mydb`.`movies` (
  `movie_id` INT NOT NULL AUTO_INCREMENT,
  `tittle` VARCHAR(45) NULL,
  `description` VARCHAR(200) NULL,
  `movie_type_id` INT NULL,
  `movie_category_id` INT NULL,
  `cover` VARCHAR(45) NULL,
  `movie_img` VARCHAR(45) NULL,
  `trailer` VARCHAR(100) NULL,
  `state` TINYINT(1) NULL,
  PRIMARY KEY (`movie_id`),
  UNIQUE INDEX `tittle_UNIQUE` (`tittle` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`movie_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`movie_type` ;

CREATE TABLE IF NOT EXISTS `mydb`.`movie_type` (
  `movie_type_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `state` TINYINT(1) NULL,
  PRIMARY KEY (`movie_type_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  CONSTRAINT `fk_movie_type_movies1`
    FOREIGN KEY (`movie_type_id`)
    REFERENCES `mydb`.`movies` (`movie_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`movie_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`movie_category` ;

CREATE TABLE IF NOT EXISTS `mydb`.`movie_category` (
  `movie_category_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `state` TINYINT(1) NULL,
  PRIMARY KEY (`movie_category_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  CONSTRAINT `fk_movie_category_movies1`
    FOREIGN KEY (`movie_category_id`)
    REFERENCES `mydb`.`movies` (`movie_category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`room` ;

CREATE TABLE IF NOT EXISTS `mydb`.`room` (
  `room_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `location` VARCHAR(45) NULL,
  `structure` JSON NULL,
  `state` SMALLINT(1) NULL,
  PRIMARY KEY (`room_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`watching`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`watching` ;

CREATE TABLE IF NOT EXISTS `mydb`.`watching` (
  `watching_id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME(30) NULL,
  `movie_id` INT NULL,
  `room_id` INT NULL,
  `state` INT NULL,
  PRIMARY KEY (`watching_id`),
  INDEX `fk_watching_movies_idx` (`movie_id` ASC) VISIBLE,
  INDEX `fk_watching_room1_idx` (`room_id` ASC) VISIBLE,
  CONSTRAINT `fk_watching_movies`
    FOREIGN KEY (`movie_id`)
    REFERENCES `mydb`.`movies` (`movie_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_watching_room1`
    FOREIGN KEY (`room_id`)
    REFERENCES `mydb`.`room` (`room_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`customers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`customers` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `names` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(105) NULL,
  `dob` DATE NULL,
  `gender` VARCHAR(6) NULL,
  `state` TINYINT(1) NULL,
  PRIMARY KEY (`customer_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`payment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`payment` (
  `payment_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NULL,
  `watching_id` INT NULL,
  `date` TIMESTAMP(50) NULL,
  `state` INT NULL,
  `approved_by` INT NULL,
  PRIMARY KEY (`payment_id`),
  INDEX `fk_payment_watching1_idx` (`watching_id` ASC) VISIBLE,
  INDEX `fk_payment_customers1_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_payment_watching1`
    FOREIGN KEY (`watching_id`)
    REFERENCES `mydb`.`watching` (`watching_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payment_customers1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mydb`.`customers` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`boocked_place`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`boocked_place` ;

CREATE TABLE IF NOT EXISTS `mydb`.`boocked_place` (
  `boocked_place_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NULL,
  `watch_id` INT NULL,
  `seat_code` INT NULL,
  `date` TIMESTAMP(30) NULL,
  `book_type_id` INT NULL,
  `payment_id` INT NULL,
  `state` VARCHAR(1) NULL,
  PRIMARY KEY (`boocked_place_id`),
  INDEX `fk_boocked_place_customers1_idx` (`customer_id` ASC) VISIBLE,
  INDEX `fk_boocked_place_payment1_idx` (`payment_id` ASC) VISIBLE,
  CONSTRAINT `fk_boocked_place_customers1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mydb`.`customers` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_boocked_place_payment1`
    FOREIGN KEY (`payment_id`)
    REFERENCES `mydb`.`payment` (`payment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`book_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`book_type` ;

CREATE TABLE IF NOT EXISTS `mydb`.`book_type` (
  `book_type_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `state` SMALLINT(1) NULL,
  PRIMARY KEY (`book_type_id`),
  CONSTRAINT `fk_book_type_boocked_place1`
    FOREIGN KEY (`book_type_id`)
    REFERENCES `mydb`.`boocked_place` (`book_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `user_id` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_users_payment1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`payment` (`approved_by`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
